# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7316a3ed4fd37b2743f5b11598a6a5ac603921ec4cb5aec9caee57a0b6251ce7a3855e2ba00599d23721fa0c898cc098a687474cc66171ad661e5ce5647e4b6e

test:
  secret_key_base: 5338234c99d7c943fd0e17eb5e71c209afeb13cc538ce5ce353d598187dfd68ee5bb6610ca4f498cb27a7e7f31de4d2ce483447211bbf34aad8cf7b285c7678d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
